-- MySQL Script generated by MySQL Workbench
-- Thu May 26 11:30:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectovn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectovn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectovn` DEFAULT CHARACTER SET utf8 ;
USE `proyectovn` ;

-- -----------------------------------------------------
-- Table `proyectovn`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`ciudad` (
  `IDciu` INT NOT NULL,
  `NomCiu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDciu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectovn`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`usuario` (
  `IDusu` INT NOT NULL AUTO_INCREMENT,
  `NomUsu` VARCHAR(45) NOT NULL,
  `ApeUsu` VARCHAR(45) NOT NULL,
  `PassUsu` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Movil` VARCHAR(45) NULL,
  `IDciu` INT NULL,
  PRIMARY KEY (`IDusu`),
  INDEX `fk_usuario_ciudad1_idx` (`IDciu` ASC),
  CONSTRAINT `fk_usuario_ciudad1`
    FOREIGN KEY (`IDciu`)
    REFERENCES `proyectovn`.`ciudad` (`IDciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectovn`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`categoria` (
  `IDcat` INT NOT NULL AUTO_INCREMENT,
  `NomCat` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`IDcat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectovn`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`empresa` (
  `IDemp` INT NOT NULL AUTO_INCREMENT,
  `NomEmp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDemp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectovn`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`actividad` (
  `IDact` INT NOT NULL AUTO_INCREMENT,
  `IDcat` INT NOT NULL,
  `IDciu` INT NOT NULL,
  `NomAct` VARCHAR(45) NOT NULL,
  `IDemp` INT NULL,
  `Horario` VARCHAR(150) NULL,
  `Info` VARCHAR(100) NULL,
  PRIMARY KEY (`IDact`),
  INDEX `fk_categoria_has_ciudad_ciudad1_idx` (`IDciu` ASC),
  INDEX `fk_categoria_has_ciudad_categoria1_idx` (`IDcat` ASC),
  INDEX `fk_actividad_empresa1_idx` (`IDemp` ASC),
  CONSTRAINT `fk_categoria_has_ciudad_categoria1`
    FOREIGN KEY (`IDcat`)
    REFERENCES `proyectovn`.`categoria` (`IDcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_ciudad_ciudad1`
    FOREIGN KEY (`IDciu`)
    REFERENCES `proyectovn`.`ciudad` (`IDciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_empresa1`
    FOREIGN KEY (`IDemp`)
    REFERENCES `proyectovn`.`empresa` (`IDemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectovn`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectovn`.`reserva` (
  `IDres` INT NOT NULL AUTO_INCREMENT,
  `IDusu` INT NOT NULL,
  `IDact` INT NOT NULL,
  `Hora` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  INDEX `fk_table1_usuario1_idx` (`IDusu` ASC),
  INDEX `fk_table1_actividad1_idx` (`IDact` ASC),
  PRIMARY KEY (`IDres`),
  CONSTRAINT `fk_table1_usuario1`
    FOREIGN KEY (`IDusu`)
    REFERENCES `proyectovn`.`usuario` (`IDusu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_actividad1`
    FOREIGN KEY (`IDact`)
    REFERENCES `proyectovn`.`actividad` (`IDact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
