-- MySQL Script generated by MySQL Workbench
-- Tue May  3 18:10:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoVN
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoVN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoVN` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoVN` ;

-- -----------------------------------------------------
-- Table `ProyectoVN`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`usuario` (
  `IDusu` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `PassUsu` VARCHAR(45) NOT NULL,
  `NomUsu` VARCHAR(45) NOT NULL,
  `ApeUsu` VARCHAR(100) NOT NULL,
  `Movil` VARCHAR(12) NULL,
  PRIMARY KEY (`IDusu`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`ciudad` (
  `IDciu` INT NOT NULL,
  `NomCiu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDciu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`categoria` (
  `IDcat` INT NOT NULL AUTO_INCREMENT,
  `NomCat` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(200) NULL,
  PRIMARY KEY (`IDcat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`empresa` (
  `IDemp` INT NOT NULL AUTO_INCREMENT,
  `NomEmp` VARCHAR(45) NOT NULL,
  `IDciu` INT NULL,
  PRIMARY KEY (`IDemp`),
  INDEX `fk_empresa_ciudad1_idx` (`IDciu` ASC),
  CONSTRAINT `fk_empresa_ciudad1`
    FOREIGN KEY (`IDciu`)
    REFERENCES `ProyectoVN`.`ciudad` (`IDciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`subcategoria` (
  `IDsub` INT NOT NULL AUTO_INCREMENT,
  `NomSub` VARCHAR(45) NOT NULL,
  `IDcat` INT NULL,
  PRIMARY KEY (`IDsub`),
  INDEX `fk_subcategoria_categoria_idx` (`IDcat` ASC),
  CONSTRAINT `fk_subcategoria_categoria`
    FOREIGN KEY (`IDcat`)
    REFERENCES `ProyectoVN`.`categoria` (`IDcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`actividad` (
  `IDact` INT NOT NULL AUTO_INCREMENT,
  `NomAct` VARCHAR(45) NOT NULL,
  `IDemp` INT NOT NULL,
  `IDsub` INT NOT NULL,
  `Horario` VARCHAR(45) NULL,
  `IDciu` INT NOT NULL,
  PRIMARY KEY (`IDact`),
  INDEX `fk_empresa_has_subcategoria_empresa1_idx` (`IDemp` ASC),
  INDEX `fk_actividad_subcategoria1_idx` (`IDsub` ASC),
  INDEX `fk_actividad_ciudad1_idx` (`IDciu` ASC),
  CONSTRAINT `fk_empresa_has_subcategoria_empresa1`
    FOREIGN KEY (`IDemp`)
    REFERENCES `ProyectoVN`.`empresa` (`IDemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_subcategoria1`
    FOREIGN KEY (`IDsub`)
    REFERENCES `ProyectoVN`.`subcategoria` (`IDsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_ciudad1`
    FOREIGN KEY (`IDciu`)
    REFERENCES `ProyectoVN`.`ciudad` (`IDciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`reservas` (
  `IDusu` INT NOT NULL,
  `IDact` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` DATETIME NOT NULL,
  PRIMARY KEY (`IDusu`, `IDact`),
  INDEX `fk_usuario_has_actividad_actividad1_idx` (`IDact` ASC),
  INDEX `fk_usuario_has_actividad_usuario1_idx` (`IDusu` ASC),
  CONSTRAINT `fk_usuario_has_actividad_usuario1`
    FOREIGN KEY (`IDusu`)
    REFERENCES `ProyectoVN`.`usuario` (`IDusu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_actividad_actividad1`
    FOREIGN KEY (`IDact`)
    REFERENCES `ProyectoVN`.`actividad` (`IDemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoVN`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoVN`.`favoritos` (
  `IDusu` INT NOT NULL,
  `IDciu` INT NOT NULL,
  PRIMARY KEY (`IDusu`, `IDciu`),
  INDEX `fk_usuario_has_ciudad_ciudad1_idx` (`IDciu` ASC),
  INDEX `fk_usuario_has_ciudad_usuario1_idx` (`IDusu` ASC),
  CONSTRAINT `fk_usuario_has_ciudad_usuario1`
    FOREIGN KEY (`IDusu`)
    REFERENCES `ProyectoVN`.`usuario` (`IDusu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_ciudad_ciudad1`
    FOREIGN KEY (`IDciu`)
    REFERENCES `ProyectoVN`.`ciudad` (`IDciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
